# Generated by Django 4.1.5 on 2024-05-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('folder_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_textdata', models.TextField()),
                ('server_location', models.TextField(default='DefaultServer', max_length=1000)),
                ('response_file_location', models.TextField(max_length=1000)),
                ('response_time_to_complete', models.FloatField(default=0.0)),
                ('systemfile_name', models.CharField(max_length=255)),
                ('userfile_name', models.CharField(max_length=255)),
                ('voice', models.CharField(max_length=255)),
                ('deletedTF', models.BooleanField(default=False)),
                ('length_of_audio_seconds', models.IntegerField(default=0)),
                ('file_sizeMB', models.FloatField(default=0.0)),
            ],
        ),
    ]
