# Generated by Django 4.2.11 on 2024-05-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NinjaAPIs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiodatabase',
            old_name='server_location',
            new_name='bucket_name',
        ),
    ]
