# Generated by Django 4.2.11 on 2024-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NinjaAPIs', '0002_rename_server_location_audiodatabase_bucket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodatabase',
            name='friends_view_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiodatabase',
            name='public_post',
            field=models.BooleanField(default=False),
        ),
    ]
