# Generated by Django 4.1.5 on 2024-04-30 23:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SignInSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='folder_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
