# Generated by Django 4.2.11 on 2024-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignInSystem', '0002_alter_customuser_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paying_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_tf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='was_once_paying_user',
            field=models.BooleanField(default=False),
        ),
    ]
